name:  GH Actions SAST
description: Static analyzer for GH actions
author: 'Kong'
inputs:
  scan_path:
    description: 'File, Dir, Repository formatted: "owner/repo[@<sha>]" containing workflow files'
    required: true
    default: '.' #Default is workspace
  github_token:
    description: 'PAT for fetching remote "scan_path" of format "owner/repo[@<sha>]"'
    required: false
    default: ''
  offline_audit_checks:
    description: "Runs offline audit checks but performs repository pulls"
    required: false
    default: false
    type: choice
    options:
    - 'true'
    - 'false'
  persona:
    description: 'Run specific audit checks based on selected persona.'
    required: false
    default: 'pedantic'
    type: choice
    options:
    - 'regular'
    - 'pedantic'
    - 'auditor'
  asset_prefix:
    description: 'prefix for generated artifacts'
    required: false
  fail_on_findings:
    description: 'Fail build / job on findings/errors'
    required: false
    default: 'false'
    type: choice
    options:
    - 'true'
    - 'false'
  codeql_upload:
    description: 'Toggle to upload results to Github code scanning for public repositories'
    required: false
    default: false
    type: choice
    options:
    - 'true'
    - 'false'

runs:
  using: 'composite'
  steps:

    - name: Set Scan metadata
      shell: bash
      id: meta
      env:
        SCAN_PATH: ${{ inputs.SCAN_PATH }}
        PERSONA: ${{ inputs.persona }}
        OFFLINE_AUDIT_CHECKS: ${{ inputs.offline_audit_checks }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ASSET_PREFIX: ${{ inputs.asset_prefix }}
      run: $GITHUB_ACTION_PATH/scripts/scan-metadata.sh

    - name: Install cargo-hack from crates.io
      uses: baptiste0928/cargo-install@91c5da15570085bcde6f4d7aed98cb82d6769fd3
      with:
        crate: zizmor
        locked: true
        version: '~1'
    
    - name: Run GH Actions SAST - [SARIF format]
      shell: bash
      id: gh_actions_sast_sarif
      # Continue on error to upload results
      continue-on-error: true
      run: |
        zizmor ${{ env.SCAN_ARGS }} ${{ env.SCAN_PATH }} --format sarif > ${{ steps.meta.outputs.sarif_file }}
      env:
        SCAN_ARGS: ${{ steps.meta.outputs.scan_args }}
        SCAN_PATH: ${{ inputs.scan_path }}
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Upload SARIF to Github Code Scanning
      if: ${{ always() && inputs.codeql_upload == 'true' && github.event.repository.visibility == 'public' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: ${{ steps.meta.outputs.sarif_file }}
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        category: gh_actions_sast
    
    - name: Run GH Actions SAST - [Plain format]
      shell: bash
      # Continue on error to upload results
      continue-on-error: true
      id: gh_actions_sast_plain
      run: |
        zizmor ${{ env.SCAN_ARGS }} ${{ env.SCAN_PATH }} --format plain > ${{ steps.meta.outputs.out_file }}
      env:
        SCAN_ARGS: ${{ steps.meta.outputs.scan_args }}
        SCAN_PATH: ${{ inputs.scan_path }}
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Upload GH Actions SAST reports to Workflow
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.meta.outputs.report_file_name }}.zip
        path: |
          ${{ steps.meta.outputs.sarif_file }}
          ${{ steps.meta.outputs.out_file}}
        if-no-files-found: warn
    
    - name: Add findings as check summary
      if: always() 
      shell: bash
      run: |
        if [[ -f "${OUT_FILE}" ]]; then
          echo "## GH Actions SAST CI Scan Summary Report" >> $GITHUB_STEP_SUMMARY
          while IFS= read -r line; do
            echo "- $line" >> $GITHUB_STEP_SUMMARY
          done < ${OUT_FILE}
        fi
      env:
        OUT_FILE: ${{ steps.meta.outputs.out_file}}

    - name: Print to console out
      if: always() 
      shell: bash
      run: |
        echo "::group::Github Actions SAST Scan Summary Report"
        if [[ -f "${OUT_FILE}" ]]; then
         cat ${OUT_FILE}
        fi
        echo "::endgroup::"   
      env:
        OUT_FILE: ${{ steps.meta.outputs.out_file}}

    - name: Fail on findings
      if: ${{ always() && steps.semgrep.outcome == 'failure' && env.fail_build == 'true' }}
      shell: bash
      run: |
        echo "::error::Semgrep has detected findings. For findings, check workflow artifact: semgrep_sast.zip / Github Security analysis"
        exit 1
      env: 
        FAIL_BUILD: ${{ steps.meta.outputs.global_enforce_build_failure == 'true' && steps.meta.outputs.global_enforce_build_failure || inputs.fail_on_findings }}