# Secrets are inherited from calling workflow within same org or enterprise
# Explicit secrets forr all other calling wortkflows outside org or enterprise

on:
  workflow_call:

    inputs:
      TARGET_SCAN_REPOSITORY:
        required: false
        description: Target repository to scan
        type: string
      TARGET_SCAN_REF:
        required: false
        description: Target ref/branch to scan
        type: string
      FAIL_SHELLCHECK_LEVEL:
        required: true
        type: string
      FAIL_ACTIONLINT_LEVEL:
        required: true
        type: string
      FAIL_GHLINT:
        required: true
        type: string
      FAIL_ZIZMOR:
        required: true
        type: string
      GHLINT_FILES_SCAN_REGEX:
        description: Space separated regex/paths to GH actions and workflow files
        required: true
        type: string
      ZIZMOR_PERSONA:
        description: zizmor sast analyzer audit persona
        required: false
        type: string
      ZIZMOR_OFFLINE_AUDIT:
        description: Run only zizmor sast analyzer offline audit checks
        required: false
        type: string
    secrets:
      TOKEN:
        required: true

# Permissions should be specified on calling workflow
# Permissions specified here in reusable workflow can only be downgraded but elevated
permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    name: shellcheck
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.TOKEN }}  # Use the passed token for checkout
          repository: ${{ inputs.TARGET_SCAN_REPOSITORY || github.repository }}
          ref: ${{ inputs.TARGET_SCAN_REF || '' }}

      - uses: reviewdog/action-shellcheck@6e0e63d1750d02d761b3df0f2c5ba9f9ac4a9ed7
        with:
          # When used as required workflow in ruleset, this parameter has can block pushes
          fail_level: ${{inputs.FAIL_SHELLCHECK_LEVEL}}
          # Run for all sh files even when not added/modified
          #filter_mode: nofilter
          filter_mode: ${{ github.event_name == 'pull_request' && 'file' || 'nofilter' }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-check' || 'github-check' }}
          check_all_files_with_shebangs: "true"
          github_token: ${{ secrets.TOKEN }}

  actionlint:
    runs-on: ubuntu-24.04
    name: actionlint
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.TOKEN }}  # Use the passed token for checkout
          repository: ${{ inputs.TARGET_SCAN_REPOSITORY || github.repository }}
          ref: ${{ inputs.TARGET_SCAN_REF || '' }}

        # shellcheck is enabled by default on scripts using the run: block within workflows
      - uses: reviewdog/action-actionlint@f3dcc52bc6039e5d736486952379dce3e869e8a2
        with:
          # When used as required workflow in ruleset, this parameter has can block pushes
          fail_level: ${{inputs.FAIL_ACTIONLINT_LEVEL}}
          # Run for all sh files even when not added/modified
          filter_mode: nofilter
          #filter_mode: ${{ github.event_name == 'pull_request' && 'file' || 'nofilter' }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-check' || 'github-check' }}
          github_token: ${{ secrets.TOKEN }}

  ghlint:
    runs-on: ubuntu-24.04
    name: ghlint
    env:
      REPORT_FILE_NAME: ghlint_report
      GHLINT_REPO: TWiStErRob/net.twisterrob.ghlint
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.TOKEN }}  # Use the passed token for checkout
          repository: ${{ inputs.TARGET_SCAN_REPOSITORY || github.repository }}
          ref: ${{ inputs.TARGET_SCAN_REF || '' }}

      - name: "Download GH-Lint"
        working-directory: ${{ runner.temp }}
        env:
          GHLINT_VERSION: '0.5.0'
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh release download --repo ${{env.GHLINT_REPO}} \
          "v${GHLINT_VERSION}" --pattern "ghlint.jar"
      
      - name: "Run GH-Lint for workflows and composite actions"
        id: ghlint
        continue-on-error: true
        run: |
          java -jar ${RUNNER_TEMP}/ghlint.jar ${{env.args}} ${{env.scan_patterns}}
        env:
          scan_patterns: ${{inputs.GHLINT_FILES_SCAN_REGEX}}
          args: >-
            --exit
            --ghcommands
            --sarif=${{env.REPORT_FILE_NAME}}.sarif

      - name: Upload GH lint report to Workflow
        if: always() && steps.ghlint.conclusion == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.REPORT_FILE_NAME}}.zip
          path: |
            ${{env.REPORT_FILE_NAME}}.sarif
          if-no-files-found: warn
      
      - name: Fail on findings
        if: always()
        run: |
          if [[ ${SCAN_STATUS} == 'failure' ]] && [[ ${FAIL_BUILD} == 'true' ]]; then
            echo "::error::ghlint has detected findings. For findings, check workflow artifact: ghlint-report.zip / Github Security analysis"
            exit 1
          fi
        env: 
          SCAN_STATUS: ${{ steps.ghlint.outcome }}
          FAIL_BUILD: "${{inputs.FAIL_GHLINT}}"
          
      # - name: "Publish 'GH-Lint' GitHub Code Scanning analysis."
      #   if: ${{  }}
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     checkout_path: ${{ github.workspace }}
      #     sarif_file: ${{ steps.ghlint.outputs.sarif-report }}

  gh-sast:
    runs-on: ubuntu-24.04
    env:
      REPO: ${{ inputs.TARGET_SCAN_REPOSITORY || github.repository }}
    steps:
      # Helps to run the scan on a local directory at the triggered ref
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ env.REPO}}
          ref: ${{ inputs.TARGET_SCAN_REF || '' }}
          path: ${{ env.REPO }}

      - name: Check GH anti-pattern using zizmor
        id: zizmor
        uses: saisatishkarra/public-shared-actions/security-actions/scan-gh-workflows@feat/gh-anti-pattern-scan
        with:
          scan_path: ${{github.workspace}}/${{env.REPO}}
          persona: ${{ inputs.ZIZMOR_PERSONA || 'pedantic' }}
          offline_audit_checks: ${{ inputs.ZIZMOR_OFFLINE_AUDIT || 'true' }}
          # When used as required workflow in ruleset, this parameter has can block pushes
          fail_on_findings: ${{inputs.FAIL_ZIZMOR}}
          codeql_upload: false
          github_token: ${{ secrets.TOKEN }}
          asset_prefix: ${{ inputs.TARGET_SCAN_REPOSITORY || github.repository }}
