name: GH Actions SAST

on:
  pull_request: {}
  merge_group: {}
  push: {}
  workflow_dispatch: {}

jobs:

  shellcheck:
    runs-on: ubuntu-24.04
    name: shellcheck
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: reviewdog/action-shellcheck@6e0e63d1750d02d761b3df0f2c5ba9f9ac4a9ed7
        with:
          # When used as required workflow in ruleset, this parameter has can block pushes
          fail_level: error
          # Run for all sh files even when not added/modified
          filter_mode: ${{ github.event_name == 'pull_request' && 'file' || 'nofilter' }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-check' || 'github-check' }}
          check_all_files_with_shebangs: "true"
    
  actionlint:
    runs-on: ubuntu-24.04
    name: actionlint
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        # shellcheck is enabled by default on scripts using the run: block within workflows
      - uses: reviewdog/action-actionlint@f3dcc52bc6039e5d736486952379dce3e869e8a2
        with:
          # When used as required workflow in ruleset, this parameter has can block pushes
          fail_level: any
          # Run for all sh files even when not added/modified
          filter_mode: ${{ github.event_name == 'pull_request' && 'file' || 'nofilter' }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-check' || 'github-check' }}

  analyze-anti-patterns:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # publish sbom to GH releases/tag assets
      actions: read
      contents: read
    steps:
      # Helps to run the scan on a local directory at the triggered ref
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run CI sanitize
        id: sanitize-ci
        uses: ./security-actions/scan-gh-workflows
        with:
          scan_path: ${{github.workspace}}
          persona: 'pedantic'
          # When used as required workflow in ruleset, this parameter has can block pushes
          fail_on_findings: false 
          codeql_upload: false
          github_token: ${{github.token}}
